-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:LG Display 0x0706",
  mode = "1920x1080@60.02",
  position = "0x216",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
