# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale


# Always on
env = GDK_SCALE,2
monitor= eDP-1,preferred,auto, 1.25


# 1) Config for laptop at left and at right monitor in Modena with hdmi
#monitor= HDMI-A-1, 1920x1080@144, auto-center-right, auto
# At left second monitor asus
monitor= DP-2, 1920x1080@60, auto-center-left,auto


# 2) Config for Milano, monitor wide at right, laptop at left
# monitor= HDMI-A-1, 2560x1080@100, auto-center-left, auto


monitor = HEADLESS-1, 1920x1080@60, 1920x0, 1